# Customer Analysis using ETL Process (Python + MySQL)

## This project demonstrates a real-world ETL pipeline using Pandas and MySQL.

## Objective: Extract customer data from CSV, transform it using Python, load it into MySQL, and perform analysis.

# 1.Read CSV using Pandas

In [2]:
import pandas as pd

df = pd.read_csv("customers.csv")

print(df.head())

   CustomerID CustomerName       City            Email   Age   JoinDate  \
0           1  Amit Sharma      Delhi   amit@gmail.com  28.0  1/10/2025
1           2    Priya Rao    Chennai  priya@gmail.com  34.0  1/15/2025
2           3  Rahul Verma     Mumbai  rahul@gmail.com  41.0   2/2/2025
3           4   Sneha Iyer  Bengaluru  sneha@gmail.com  29.0  2/12/2025
4           5  Kiran Kumar  Hyderabad  kiran@gmail.com  37.0   3/5/2025

   TotalPurchase
0        12500.0
1        22000.0
2        18500.0
3         9800.0
4        31000.0

# 2.Clean and transform data – handle data duplications and nulls and perform aggregation with total purchase by all customers.

In [4]:
# Remove Duplicates
df = df.drop_duplicates()

In [7]:
# Handle Null Values
df = df.fillna(0)
df = df.dropna()

In [8]:
# Data Type Conversion
df["CustomerID"] = df["CustomerID"].astype(int)

df["Age"] = df["Age"].astype(int)

In [9]:
#Total Purchase Aggregation
total_revenue = df["TotalPurchase"].sum()

print(total_revenue)

155800.0

In [10]:
!pip install pandas mysql-connector-python sqlalchemy

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   -- ------------------------------------- 1.3/17.7 MB 25.8 MB/s eta 0:00:01
   --------- ------------------------------ 4.2/17.7 MB 22.7 MB/s eta 0:00:01
   ---------- ----------------------------- 4.5/17.7 MB 16.4 MB/s eta 0:00:01
   ------------ --------------------------- 5.5/17.7 MB 8.7 MB/s eta 0:00:02
   ------------- -------------------------- 6.0/17.7 MB 6.8 MB/s eta 0:00:02
   --------------- ------------------------ 6.8/17.7 MB 6.5 MB/s eta 0:00:02
   ----------------- ---------------------- 7.6/17.7 MB 5.9 MB/s eta 0:00:02
   ------------------ --------------------- 8.1/17.7 MB 5.6 MB/s eta 0:00:02
   -------------------- ------------------- 8.9/17.7 MB 5.2 MB/s eta 0:00:02
   --------------------- ------------------ 9.4/17.7 MB 5.0 MB/s eta 0:00:02
   ----------------------- ---------------- 10.2/17.7 MB 4.8 MB/s eta 0:00:02
   ------------------------ --------------- 10.7/17.7 MB 4.7 MB/s eta 0:00:02
   -------------------------- ------------- 11.5/17.7 MB 4.5 MB/s eta 0:00:02
   --------------------------- ------------ 12.1/17.7 MB 4.5 MB/s eta 0:00:02
   ----------------------------- ---------- 12.8/17.7 MB 4.3 MB/s eta 0:00:02
   ------------------------------ --------- 13.4/17.7 MB 4.3 MB/s eta 0:00:02
   ------------------------------- -------- 13.9/17.7 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 14.7/17.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------- ----- 15.5/17.7 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 16.0/17.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 16.5/17.7 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 3.9 MB/s  0:00:04
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

# 3.Load into MySQL
Build analytical queries for the below problem statements.

In [12]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Bhawna@123@localhost:3306/hr"
)

In [16]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Bhawna%40123@localhost:3306/hr"
)

try:
    with engine.connect() as conn:
        print("MySQL Connected Successfully")
except Exception as e:
    print("Connection Failed")
    print(e)

MySQL Connected Successfully

In [17]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE();"))
    print(result.fetchone())

('hr',)

In [18]:
# Load Customer Table
df.to_sql(
    "Customers",
    con=engine,
    if_exists="replace",
    index=False
)

C:\Users\hp\AppData\Local\Temp\ipykernel_40844\1367040755.py:2: UserWarning: The provided table name 'Customers' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(

10

In [19]:
# Validate Load
pd.read_sql(
    "SELECT * FROM Customers",
    con=engine
)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28,1/10/2025,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34,1/15/2025,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41,2/2/2025,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29,2/12/2025,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37,3/5/2025,31000.0
5,6,Anjali Gupta,Pune,anjali@gmail.com,26,3/15/2025,7600.0
6,7,Vikram Singh,Delhi,vikram@gmail.com,0,4/1/2025,0.0
7,8,Neha Patel,Ahmedabad,neha@gmail.com,31,4/10/2025,15400.0
8,9,Arjun Reddy,Chennai,arjun@gmail.com,39,5/2/2025,27800.0
9,10,Meera Nair,Kochi,meera@gmail.com,27,5/18/2025,11200.0

In [30]:
customer_summary = df.groupby("City")["TotalPurchase"].sum().reset_index()

customer_summary

        City  TotalPurchase
0  Ahmedabad        15400.0
1  Bengaluru         9800.0
2    Chennai        49800.0
3      Delhi        12500.0
4  Hyderabad        31000.0
5      Kochi        11200.0
6     Mumbai        18500.0
7       Pune         7600.0

In [31]:
df.to_sql(
    name="customers",
    con=engine,
    if_exists="replace",
    index=False
)

customer_summary.to_sql(
    name="customer_summary",
    con=engine,
    if_exists="replace",
    index=False
)

print("ETL Load Completed")

ETL Load Completed

# Build analytical queries for the below problem statements.

# 4.Find top customers by purchase

In [32]:
pd.read_sql("""
SELECT CustomerID,
       CustomerName,
       TotalPurchase
FROM Customers
ORDER BY TotalPurchase DESC
""", con=engine)

   CustomerID  CustomerName  TotalPurchase
0           5   Kiran Kumar        31000.0
1           9   Arjun Reddy        27800.0
2           2     Priya Rao        22000.0
3           3   Rahul Verma        18500.0
4           8    Neha Patel        15400.0
5           1   Amit Sharma        12500.0
6          10    Meera Nair        11200.0
7           4    Sneha Iyer         9800.0
8           6  Anjali Gupta         7600.0
9           7  Vikram Singh            0.0


# 5.Analyze city-wise revenue

In [33]:
pd.read_sql("""
SELECT City,
       SUM(TotalPurchase) AS Revenue
FROM Customers
GROUP BY City
""", con=engine)

        City  Revenue
0      Delhi  12500.0
1    Chennai  49800.0
2     Mumbai  18500.0
3  Bengaluru   9800.0
4  Hyderabad  31000.0
5       Pune   7600.0
6  Ahmedabad  15400.0
7      Kochi  11200.0

 # 6.Rank customers using window functions

In [34]:
pd.read_sql("""
SELECT CustomerID,
       CustomerName,
       TotalPurchase,
       DENSE_RANK() OVER(
           ORDER BY TotalPurchase DESC
       ) AS RankNo
FROM Customers
""", con=engine)

   CustomerID  CustomerName  TotalPurchase  RankNo
0           5   Kiran Kumar        31000.0       1
1           9   Arjun Reddy        27800.0       2
2           2     Priya Rao        22000.0       3
3           3   Rahul Verma        18500.0       4
4           8    Neha Patel        15400.0       5
5           1   Amit Sharma        12500.0       6
6          10    Meera Nair        11200.0       7
7           4    Sneha Iyer         9800.0       8
8           6  Anjali Gupta         7600.0       9
9           7  Vikram Singh            0.0      10

# 7. Total Customers

In [35]:
pd.read_sql("""
SELECT COUNT(*) AS TotalCustomers
FROM Customers
""", con=engine)

   TotalCustomers
0              10


# 8. City-wise Customer Count

In [36]:
pd.read_sql("""
SELECT City,
       COUNT(*) AS CustomerCount
FROM Customers
GROUP BY City
""", con=engine)

        City  CustomerCount
0      Delhi              2
1    Chennai              2
2     Mumbai              1
3  Bengaluru              1
4  Hyderabad              1
5       Pune              1
6  Ahmedabad              1
7      Kochi              1

# 9. City-wise Revenue

In [37]:
pd.read_sql("""
SELECT City,
       SUM(TotalPurchase) AS Revenue
FROM Customers
GROUP BY City
""", con=engine)

        City  Revenue
0      Delhi  12500.0
1    Chennai  49800.0
2     Mumbai  18500.0
3  Bengaluru   9800.0
4  Hyderabad  31000.0
5       Pune   7600.0
6  Ahmedabad  15400.0
7      Kochi  11200.0

# 10. fetch Above Average Customers information

In [42]:
pd.read_sql("""
SELECT *
FROM Customers
WHERE TotalPurchase >
(
    SELECT AVG(TotalPurchase)
    FROM Customers
)
""", con=engine)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,2,Priya Rao,Chennai,priya@gmail.com,34,1/15/2025,22000.0
1,3,Rahul Verma,Mumbai,rahul@gmail.com,41,2/2/2025,18500.0
2,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37,3/5/2025,31000.0
3,9,Arjun Reddy,Chennai,arjun@gmail.com,39,5/2/2025,27800.0

In [43]:
# 11. find Customer Acquisition Trend

In [45]:
pd.read_sql("""
SELECT DATE_FORMAT(JoinDate,'%Y-%m') AS Month,
       COUNT(*) AS NewCustomers
FROM Customers
GROUP BY DATE_FORMAT(JoinDate,'%Y-%m')
ORDER BY Month
""", con=engine)

  Month  NewCustomers
0  None            10